Arquivos já em jsx da página login
taernsietr/IC819-front pull request #17
Opened 2022-08-03 01:07 UTC by Maxcravo

[Enviando os arquivos já em JSX do projeto, faltando a responsividade.

2022-08-03 01:10 UTC, taernsietr commented on src/front/components/LoginInput/LoginInput.css
> +.LoginDiv{
eu quero morrer

2022-08-03 01:12 UTC, irizzo approved these changes
- Arrumar: nome de classe com nome maiúsculo não, colocar minúsculo

2022-08-03 01:12 UTC, taernsietr requested changes
- classes devem começar sempre com letra minúscula, IMHO;
- corrigir espaçamento dentro dos blocos de CSS;
- adicionar espaços entre os seletores e os blocos

2022-08-03 01:17 UTC, gpbezerra requested changes
arrumar nome das classes padrão camelCase;
corrigir espaçamento dentro dos blocos de CSS;
corrigir espaçamento entre os elementos no html (maximo 1 linha);

2022-08-08 20:54 UTC, taernsietr approved these changes
Ainda fiquei incomodado com as classes {alguma coisa}Div, mas vou aprovar. Mas no futuro, IMO a gente muda isso.

2022-08-09 02:04 UTC, merged